title: ikl.
email: 132@ikl.sh
description: >- # this means to ignore newlines until "baseurl:"
  a random assortment of tech stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: 132ikl

# Build settings
markdown: kramdown
theme: jekyll-theme-hydeout
plugins:
    - jekyll-last-modified-at
