version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:latest 
        environment: 
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: install dependencies
          command: |
              gem update --system
              gem install bundler
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
      machine:
          enabled: true
      steps:
          - add_ssh_keys:
              fingerprints:
                  - "d5:06:7d:98:a7:88:ab:5a:4e:79:88:13:71:0c:45:c7"
          - attach_workspace:
              at: ./
          - run:
              name: Deploy site
              command: |
                  rsync -av --delete ./_site/ website@ikl.sh:./_site




workflows:
    deploy-website:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
